Try to guess the correct iptables version when it is't installed yet
Some features (like connection marking) require command line
arguments which are different between iptables version.

When iptables isn't installed yet when puppet is executed
then the current code assumes that a modern version of iptables
will get installed later on. This assumption fails on RHEL5
environments as the provided iptables version doesn't recognize
the argument '--set-xmark' and results in errors like:

Error: Execution of '/sbin/iptables -I PREROUTING 1 -t mangle -d 192.168.5.211/32 -p tcp -m multiport --dports 14201 -m comment --comment 300_foo -j MARK --set-xmark 0x67' returned 2: iptables v1.3.5: Unknown arg `--set-xmark

Resolve this by guessing the iptables version (when iptables
itself isn't installed yet) based on the OS version